apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicine-front
  namespace: front
spec:
  template:
    spec:
      containers:
      - name: medicine-front-container
        image: goodbirdacr.azurecr.io/medicine/front:stg
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
