apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
- name: app-config
  literals:
    - ENV=development
    - DEBUG=true

images:
  - name: goodbirdacr.azurecr.io/medical/front
    newName: goodbirdacr.azurecr.io/medical/front
    newTag: dev

patches:
  - path: patch_deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: front-end-deployment
      namespace: front
