apiVersion: apps/v1
kind: Deployment
metadata:
  name: metahospital-front
  namespace: front
spec:
  template:
    spec:
      containers:
      - name: metahospital-front-container
        image: goodbirdacr.azurecr.io/metahospital/front
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
