apiVersion: apps/v1
kind: Deployment
metadata:
  name: metahospital-front
  namespace: front
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: metahospital-front
  template:
    metadata:
      labels:
        app: metahospital-front
    spec:
      containers:
      - name: metahospital-front-container
        image: goodbirdacr.azurecr.io/metahospital/front:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
