apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicine-front
  namespace: front
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: medicine-front
  template:
    metadata:
      labels:
        app: medicine-front
    spec:
      containers:
      - name: medicine-front-container
        image: goodbirdacr.azurecr.io/medicine/front:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
