apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: front 

resources:
- deployment.yaml
- service.yaml

images:
- name: goodbirdacr.azurecr.io/metahospital/front
  newName: goodbirdacr.azurecr.io/metahospital/front
  newTag: latest
